### ISSUE TITLE
Improving design of emoji 12.2

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#106]
_A branch from #72_ 

## Face emojis with hands 
We have 5 fingers in these emoji [Face With Finger Covering Closed Lips](https://emojipedia.org/face-with-finger-covering-closed-lips/) and [Thinking Face](https://emojipedia.org/thinking-face/) and I think we should have 5 fingers in these emoji too
- [ ]     4 fingers - [smiling face with smiling eyes and hand covering mouth](https://emojipedia.org/smiling-face-with-smiling-eyes-and-hand-covering-mouth/)
- [ ]     4 fingers - [Yawning Face](https://emojipedia.org/yawning-face/)
- [ ]     4 fingers - [Hugging Face]( https://emojipedia.org/hugging-face/) Also hands are too low

## Other
- [x] Remove shadows from hearts - #69 
- [x] [authority instruction](/) - connect lines to improve black and white appearance, yellow of face should connect to hat - 9996cbd
- [x] [hibiscus](https://emojipedia.org/🌺/) - Should only have 5 leaves - 7efdf57
- [x] [flamingo](https://emojipedia.org/🦩/) - [tweet](https://twitter.com/WindyFlamingo/status/1205302504898080772) - one leg should be straight and with pink stroke - 7fd21d5
- [x] [light bulb](https://emojipedia.org/💡/) - [tweet](https://twitter.com/TubeTimeUS/status/1192629200496156672) - should have a screw thread on the base - aa45e23
- [x] [zany face](https://emojipedia.org/🤪/) - [tweet](https://twitter.com/_saysooo/status/1194065104528035840) - have mouth be inline with eyes - f0107ec
- [x] [horse](https://emojipedia.org/🐎/) - [tweet](https://twitter.com/jelenawoehr/status/1191877085200961536) - missing hind leg - 1a0d6f8
- [x] [donkey](https://openmoji.org/library/#group=extras-openmoji&emoji=E001) - missing hind leg - 1a0d6f8
- [x] [radioactive](https://emojipedia.org/radioactive/) and [biohazard](https://emojipedia.org/biohazard/) should match - 0990325
- [x] [sari](https://emojipedia.org/🥻) - [tweet](https://twitter.com/sridatta_a/status/1187953886608257030) - Add folds and more - #133
- [x] [bar chart](https://emojipedia.org/📊) - [tweet one](https://twitter.com/data_sci_lab/status/1233856041877753867), [tweet two](https://twitter.com/infowetrust/status/1234570766777110528)- Very Poor - Probably fine for our emoji, but would be good to incorporate axis if possible. Also white background shoudl be added, also fix the intersection with the green bar - 539d2cb and 1cf563e1
- [x] [hamburger](https://emojipedia.org/hamburger/) - Poor, should have tomato and lettuce, top bun shouldn't be a semicircle - 8187e8a
- [x] signs in Aries, Gemini, Virgo, Scorpio, Capricorn, Libra, Sagittarius - 9dc08d4
- [x] other purple square emojis Om, Cross, Wheel of Dharma, Taurus, Cancer, Leo, Aquarius, Pisces, Ophiuchus - 041fcff
- [ ] [ok hand sign](https://emojipedia.org/ok-hand-sign/) This and Pinching Hand above look like they have webbed fingers when displayed on a dark background. This will require a lot of thought and discussion to fix - #86 
- [ ] [raccoon](https://emojipedia.org/🦝/) - [tweet](https://twitter.com/formidabelle/status/1218732752637325317) - change tail to be bushier and add white to the face
- [ ] [bee](https://emojipedia.org/🐝/) - [tweet 1](https://twitter.com/molleindustria/status/1204785455666991105) [tweet 2](https://twitter.com/TyrantOverlord/status/1180168261067067393) - looks like an angel, not anatomically similar to a bee
- [ ] [teddy bear](https://emojipedia.org/🧸/) - [tweet](https://twitter.com/watery_day/status/1194369208244523008) - Poor - not cute enough :(
- [ ] [kimono](https://emojipedia.org/👘/) - [tweet](https://twitter.com/hellogeri/status/1233782147095420929) - Very Poor
- [ ] [sloth](https://emojipedia.org/🦥/) - Poor
- [ ] [dagger](https://emojipedia.org/🗡/) - [tweet](https://twitter.com/caturnsrings/status/1229643177105199104) - change way handle connects to hilt
- [ ] [cactus](https://emojipedia.org/🌵/) - [tweet](https://twitter.com/kammysayshi/status/1226070918922936326) -  arms should be the same colour, have some spines
- [ ] [train car](https://emojipedia.org/🚃/) - [tweet](https://twitter.com/MaartjeME/status/1234076348999766016) - Poor - hide the wheels
- [ ] [amphora](https://emojipedia.org/🏺/) - [tweet](https://twitter.com/GettyMuseum/status/1233224723246379008) - Very Poor, thicker handles, design should be geometric, not block shapes
- [ ] [classical building](https://emojipedia.org/🏛/) - [tweet](https://twitter.com/GettyMuseum/status/1233569422947733504) - Very Poor, should have 4 columns, should be more structural (?)
- [ ] [bowl with spoon](https://emojipedia.org/🍜/) - [tweet](https://twitter.com/jonrohan/status/1233893776222875650) - Very Poor - Bowl should at least have a flat base, curved spoon would be a plus 
- [ ] [guardsman](https://emojipedia.org/💂‍♀️/) - [tweet](https://twitter.com/NAM_London/status/1233818665398788096) - Very Poor - hat should be domed among a lot of other adjustments
- [ ] [book pile](https://emojipedia.org/📚/) - [tweet](https://twitter.com/book_historia/status/1233511440561999872) - Very Poor - too simple, don't look like real books, should show edge of pages
- [ ] [moyai - easter island head](https://emojipedia.org/🗿/) - [tweet](https://twitter.com/RapanuiPioneers/status/1233084124161826817) - Very Poor, see source for criticism
- [ ] [monkey](https://emojipedia.org/🐒) - back left leg should be defined in shape
- [ ] [microscope](https://emojipedia.org/🔬/) - [tweet](https://twitter.com/samezrael/status/1236563049676288000) - [tweet](https://twitter.com/samezrael/status/1236563049676288000) - Poor, see tweet
- [ ] [mosque](https://emojipedia.org/🕌/) - [tweet](https://twitter.com/japhettaula/status/1236588976321908737) - should be one structure
- [ ] [hippopatamus](https://emojipedia.org/hippopotamus/) - too simple, mouth should be bigger
- [ ] [llama](https://emojipedia.org/🦙/) - neck should be thicker

**Comment by b-g** [comment]
Many thanks for this! Yes there is room for improvement :)

- Yes to 5 fingers!
- Would not touch: ok sign (this needs a general plan/approach, which we still don't have)
- Raccoon: I'm happy with it as it is, but also no problem to see an alternative ... but find it really low prio and I find diversity accross different vendors no problem (as long we are equally "readable")
- Horse: yes please 4 legs!

cc @dnlutz

**Comment by carlinmack** [comment]
Racoon isn't a consistency thing, I just don't visually associate the current design with a raccoon on first glance, we can keep the perspective but maybe add more distinctive markings/change silhouette to be more raccoon like

**Comment by carlinmack** [comment]
Looking at it I think it's the tail and lack of white on the face that makes it look more monkey-ish

**Comment by b-g** [comment]
@carlinmack I see ... yes looking on it from the perspective one might confuse it. Please make the  racoon more racoon! :) Again no problem to see alternatives even if not based on the silhouette.

**Comment by b-g** [comment]
Issue #115 reminded me on another good feedback:

- [ ] Improve Sari

>  while others are designed by those who are clueless how a sari looks/is wore.
https://twitter.com/sridatta_a/status/1187953886608257030

**Comment by carlinmack** [comment]
Closing this to replace with issue #142 for the next iteration
