### ISSUE TITLE
Unicode Emoji 13

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji#124]
This is collect and coordinate upcoming Unicode Emoji 13:

- https://emojipedia.org/emoji-13.0/
- https://unicode.org/emoji/charts-13.0/emoji-released.html

## To Do
- [x] - [1FAC0](https://github.com/hfg-gmuend/openmoji/blob/Emoji13/src/people-body/body-parts/1FAC0.svg) - anatomical heart - 1bf5bcd
- [x] - [1FAC1](https://github.com/hfg-gmuend/openmoji/blob/Emoji13/src/people-body/body-parts/1FAC1.svg) - lungs - 1bf5bcd
- [x] - [1FAC2](https://github.com/hfg-gmuend/openmoji/blob/Emoji13/src/people-body/person-symbol/1FAC2.svg) - people hugging
- [x] - [1F3F3 FE0F 200D 26A7 FE0F](https://github.com/hfg-gmuend/openmoji/blob/Emoji13/src/flags/flag/1F3F3-FE0F-200D-26A7-FE0F.svg) - transgender flag - eaffd62
- [x] - [1F43B](https://github.com/hfg-gmuend/openmoji/blob/Emoji13/src/animals-nature/animal-mammal/1F43B-200D-27440-E0F.svg) - polar bear - #131 
- [x] - [1FAD0](https://github.com/hfg-gmuend/openmoji/blob/Emoji13/src/food-drink/food-fruit/1FAD0.svg) - blueberries - #134
- [x] - [1FAD3](https://github.com/hfg-gmuend/openmoji/blob/Emoji13/src/food-drink/food-prepared/1FAD3.svg) - flatbread - #134
- [x] - [1FAD4](https://github.com/hfg-gmuend/openmoji/blob/Emoji13/src/food-drink/food-prepared/1FAD4.svg) - tamale - #134
- [x] - [1FA85](https://github.com/hfg-gmuend/openmoji/blob/Emoji13/src/activities/game/1FA85.svg) - piñata - #134
- [x] - [1FA98](https://github.com/hfg-gmuend/openmoji/blob/Emoji13/src/objects/musical-instrument/1FA98.svg) - long drum - #134
- [x] - [1F972](https://github.com/hfg-gmuend/openmoji/blob/Emoji13/src/smileys-emotion/face-affection/1F972.svg) - smiling face with tear - #138 
- [x] - [1F978](https://github.com/hfg-gmuend/openmoji/blob/Emoji13/src/smileys-emotion/face-hat/1F978.svg) - disguised face - #138 
- [x] - [1F6FB](https://github.com/hfg-gmuend/openmoji/blob/Emoji13/src/travel-places/transport-ground/1F6FB.svg) - pickup truck - #138 
- [x] - 1FAB0 - fly - #138 
- [x] - 1FAB1 - worm - #138 
- [x] - 1FAD2 - olive - #138 
- [x] - 1FA84 - magic wand - #138 
- [x] - 1F6FC - roller skate - #138 
- [x] - 1FA86 - nesting dolls - #138 
- [x] - 1FA74 - thong sandal - #138 
- [x] - 1FAA5 - toothbrush - #138 
- [x] - 26A7 - transgender symbol - f36af81
- [x] - 1F408 - black cat - 94f08e2
- [x] - 1FAA0 - plunger - #138 
- [x] - 1FAA4 - mouse trap - #138 
- [x] - 1FAA3 - bucket - #138 
- [x] - 1FAA6 - headstone - #138 
- [x] - 1FAA7 - placard - #138 
- [x] - 1FAB6 - feather - #138 
- [x] - 1FAB4 - potted plant - #138 
- [x] - 1FAA1 - sewing needle - #138 
- [x] - 1FA83 - boomerang - #138 
- [x] - 1FA9A - carpentry saw - #138 
- [x] - 1FA9B - screwdriver - #138 
- [x] - 1FA9D - hook - #138 
- [x] - 1FA9E - mirror
- [x] - 1F90C - pinched fingers
- [x] - 1F9D1 - ninja
- [x] - 1F977 - person in tuxedo
- [x] - 1F935 - person with veil
- [x] - 1F470 - woman feeding baby
- [x] - 1F469 - man feeding baby
- [x] - 1F468 - person feeding baby
- [x] - 1F9D1 - mx claus
- [x] - 1F9AC - bison
- [x] - 1F9A3 - mammoth
- [x] - 1F9AB - beaver
- [x] - 1F9A4 - dodo
- [x] - 1F9AD - seal
- [x] - 1FAB2 - beetle
- [x] - 1FAB3 - cockroach
- [x] - 1FAD1 - bell pepper
- [x] - 1FAD5 - fondue
- [x] - 1FAD6 - teapot
- [x] - 1F9CB - bubble tea
- [x] - 1FAA8 - rock
- [x] - 1FAB5 - wood
- [x] - 1F6D6 - hut
- [x] - 1FAA2 - knot
- [x] - 1FA96 - military helmet
- [x] - 1FA97 - accordion
- [x] - 1FA99 - coin
- [x] - 1FA9C - ladder
- [x] - 1F6D7 - elevator
- [x] - 1FA9F - window

**Comment by carlinmack** [comment]
They've finalised the list https://unicode.org/emoji/charts-13.0/emoji-released.html

**Comment by b-g** [comment]
Yay! Thanks for the note and the todo list! Added an issue to https://github.com/milesj/emojibase/issues/45 ... hopefully emojibase is soon up to speed with Emoji 13.

**Comment by b-g** [comment]
@carlinmack @dnlutz 

FYI: March 10

> The emoji specification (UTS #51) will have additional guidelines on gender and skin tone, and other clarifications. The definitions in UTS #51 and data files have been enhanced to be more consistent and useful. The final text will be available on March 10.

> The CLDR names and search keywords for the new emoji in over 80 languages, and the sort order for emoji, will be finalized by mid-April with the release of CLDR v37.

https://github.com/milesj/emojibase/issues/45#issuecomment-580855815

**Comment by Rik44444** [comment]
hello! any need here for people who are not designers, to help review perhaps or choose between different variants?

**Comment by b-g** [comment]
@Rik44444 Many thanks for the offer, we will keep that in mind! But currently the bottleneck in terms of labour is on designing new emojis and on dev code task e.g. #135 #112  ... Are you good with code? ;)

**Comment by Rik44444** [comment]
> 
> 
> @Rik44444 Many thanks for the offer, we will keep that in mind! But currently the bottleneck in terms of labour is on designing new emojis and on dev code task e.g. #135 #112 ... Are you good with code? ;)

still in the beginning of learning, sorry! Good luck and let me know if i can help from a user perspective!

**Comment by b-g** [comment]
@carlinmack 

> RE: just to let you know I'm going to add Bravo's emojis on the Emoji13 branch tonight :) I think it's best to keep them separated until emojibase updates

Great that you are on it! Just I'm not sure whether to keep them separated is the best strategy ... IMO it would be a pity not to include the already existing Emoji 13 ones in the very soon upcoming release. (Just waiting on two new emojis from Daniel, then I would like to do a 12.2 release). Also if we don't add them to openmoji.json they won't be included in the tests and other workflow things e.g. generating pngs files etc.

Hence what about adding temporarily all emojis v13 to `data/extras-openmoji.csv`? We already know the final groups and subgroups (https://unicode.org/emoji/charts-13.0/emoji-released.html) ... and with this hack we should be able to use our normal tooling until emojibase is ready. Once this is the case we just have to copy the related rows from `data/extras-openmoji.csv` to `data/enhancements-emoji-unicode-data.csv` and are done.

What do you think?

**Comment by carlinmack** [comment]
if there's going to be a release then sure :)

**Comment by b-g** [comment]
@carlinmack FYI I've updated to emojibase-data Emoji v13 ... there is a list with everything missing for v13 here: `[data/openmoji-emoji-unicode-missing.csv](https://github.com/hfg-gmuend/openmoji/blob/master/data/openmoji-emoji-unicode-missing.csv)`. The list is automatically update via `node helpers/generate-data-tables.js`

**Comment by carlinmack** [comment]
Great, I'm in self-quarantine for the foreseeable, one silver-lining is I can work on this :)

Non-contagiously, Carlin :)

**Comment by b-g** [comment]
Yes ... Same here! 🦠 :( Will ping Liz for updates on #138 ... and then release tomorrow 12.2. Please let me know if there any reason to wait.

**Comment by carlinmack** [comment]
thanks for doing all the moving and renaming of the emoji 13s!

**Comment by carlinmack** [comment]
let me know if I can do anything 👍

**Comment by OMGShay** [comment]
Flags to add:

1. Sark
2. Brecqhou
3. Abkhazia
4. Sark
5. Savoy
6. Seborga
7. Aboriginal flag
8. Northern Ireland
9. Yugoslavia
10. Isle of Scilly
11. Isle of Wight
12. Herm
13. Hebrides
14. West Hebrides
15. Somaliland
16. San Juan
17. Rodrigues
18. Midway Atoll
19. Johnston Atoll
20. Anjouan
21. Scotland (royal)
22. Nevis

**Comment by carlinmack** [comment]
@OMGShay could you cite where you got this list from?

**Comment by OMGShay** [comment]
Here are all the flags. If you want to get them, here is the link: Animated gifs flags the Nations of the world

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Animated gifs flags the Nations of the world


 |

 |

 |


Best regards,
Shay Ebanks McDonald
    On Sunday, 3 May 2020, 15:12:20 BST, Carlin MacKenzie <notifications@github.com> wrote:  
 
 


@OMGShay could you cite where you got this list from?

**Comment by b-g** [comment]
Hi @OMGShay! We are not planning to add flags which are not part of Unicode Emoji 13. Also flags like "Yugoslavia" are tricky for historical reasons. I believe we should not support them at all. But you are welcome to contribute non-controversial ones.

**Comment by OMGShay** [comment]
You idiot!

**Comment by b-g** [comment]
@OMGShay Mind you language! You will be blocked from the OpenMoji project for the next 30 days. If this happens again forever.

**Comment by nicdiac** [comment]
@b-g Hi! :) I'm Nico, from Argentina. I'm an amateur designer (yet) and I just discover the OpenMoji project. I'm in love of all what you all have done here and I wanna colaborate in anything I can. I had a wide knowledge of Ai and Ps, and some theory of design.

**Comment by b-g** [comment]
Hi @nicdiac, Nice to e-meet you! Many thanks for the compliments! Sounds great! We definitely could need a 🖐! :)

I would suggest:
1. Read CONTRIBUTE.md
2. Pick an easier todo/issue to get familiar with the styleguide, maybe? #150 
3. Once you are bit a familiar with everything ... we could need help designing new OpenMojis e.g. #124 or all the [special interest ones](https://github.com/hfg-gmuend/openmoji/issues?q=add+special+interest+is%3Aopen+).

OK?

**Comment by nicdiac** [comment]
Perfect! :) I'm just learning how GitHub platform works, so just noticed that this is already a project 😅 I'll read it all and put in to it! Thanks

**Comment by carlinmack** [comment]
don't worry about the intricacies of github, it's perfectly possible for you to contribute like #138 :) I would maybe suggest #142 or #143 as easy issues to fix 

Glad to have you onboard!

**Comment by Funmoring46** [comment]
Hello, can I please make 1FA9C - ladder

**Comment by carlinmack** [comment]
All done by liz bravo! her emojis can be viewed in #138. This issue will be closed when the emojis are added to the project (probably before the end of the month)

Sorry @Funmoring46, she submitted a design before you made your comment. Lots of easy issues in #142 or #143 though!

**Comment by b-g** [comment]
Done! Yay! Next 13.1 :)
