### ISSUE TITLE
Emoji 15.0 support

### ISSUE THREAD

**Issue by Joshix-1** [hfg-gmuend/openmoji#410]
Unicode Emoji 15.0 has been released. Openmoji should support the new emoji.

https://www.unicode.org/emoji/charts-15.0/emoji-versions.html
https://emojipedia.org/emoji-15.0/

- [x] [U+1FAE8](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1fae8) 	🫨 	shaking face
- [x] [U+1FA77](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1fa77) 	🩷 	pink heart
- [x] [U+1FA75](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1fa75) 	🩵 	light blue heart
- [x] [U+1FA76](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1fa76) 	🩶 	grey heart
- [x] [U+1FAF7](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1faf7) 	 	🫷 	leftwards pushing hand + skin tone variants
- [x] [U+1FAF8](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1faf8) 		🫸 	rightwards pushing hand + skin tone variants
- [x] [U+1FACE](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1face) 	🫎 	moose
- [x] [U+1FACF](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1facf) 		🫏 	donkey ( https://openmoji.org/library/emoji-E001/ )
- [x] [U+1FABD](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1fabd) 	🪽 	wing
- [x] [U+1F426 U+200D U+2B1B](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1f426_200d_2b1b) 	🐦‍⬛ 	black bird
- [x] [U+1FABF](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1fabf) 	 	🪿 	goose
- [x] [U+1FABC](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1fabc) 	🪼 	jellyfish
- [x] [U+1FABB](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1fabb) 	🪻 	hyacinth
- [x] [U+1FADA](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1fada) 	🫚 	ginger root
- [x] [U+1FADB](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1fadb) 	🫛 	pea pod
- [x] [U+1FAAD](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1faad) 	🪭 	folding hand fan
- [x] [U+1FAAE](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1faae) 	🪮 	hair pick
- [x] [U+1FA87](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1fa87) 	🪇 	maracas
- [x] [U+1FA88](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1fa88) 	🪈 	flute
- [x] [U+1FAAF](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1faaf) 	 	🪯 	khanda
- [x] [U+1F6DC](https://www.unicode.org/emoji/charts-15.0/emoji-list.html#1f6dc) 	🛜 	wireless  ( https://openmoji.org/library/emoji-E254/ )

**Comment by b-g** [comment]
Hi @Joshix-1, many thanks for the gentle push. Yes! :) I believe @dnlutz is already on it. But of course ... any help is welcome.

**Comment by jyo0329** [comment]
https://github.com/hfg-gmuend/openmoji/issues/446

**Comment by jyo0329** [comment]
![すべて水色](https://user-images.githubusercontent.com/129174637/232291248-bb79c0bb-2d5b-4acf-8856a89cc111c72.svg)
I thought that the blue circles, hearts, and squares were very light blue

**Comment by Joshix-1** [comment]
All 15.0 emojis have been added. Now only a new release is missing

**Comment by SecularSteve** [comment]
Don't forget that 15.1 is a bit bigger:

https://blog.emojipedia.org/whats-new-in-unicode-15-1-and-emoji-15-1/

Or at the very least a lot more advanced.

Particular emphasis on the new ZWJ (Zero Width Joiner) Sequence Combinations in particular between multiple Emojis.

**‍‍‍U+200D**

```
Zero Width Joiner (ZWJ) is a Unicode character that joins two or more other characters together in sequence to create a new emoji.

Zero Width Joiner, pronounced "zwidge", is not an emoji and has no appearance by itself. This is an invisible character when used alone.

View [Emoji ZWJ Sequences](https://emojipedia.org/emoji-zwj-sequence/) that use this character.
Zero Width Joiner was approved as part of [Unicode 1.1](https://emojipedia.org/unicode-1.1) in 1993 and added to [Emoji 11.0](https://emojipedia.org/emoji-11.0) in 2018.
```

Some examples:

[🙂‍↔️ Head Shaking Horizontally](https://emojipedia.org/head-shaking-horizontally/?ref=blog.emojipedia.org)
    [🙂‍↕️ Head Shaking Vertically](https://emojipedia.org/head-shaking-vertically/?ref=blog.emojipedia.org)
    [🐦‍🔥 Phoenix](https://emojipedia.org/phoenix-bird/?ref=blog.emojipedia.org)
    [🍋‍🟩 Lime](https://emojipedia.org/lime/?ref=blog.emojipedia.org)
    [🍄‍🟫 Brown Mushroom](https://emojipedia.org/brown-mushroom/?ref=blog.emojipedia.org)
    [⛓️‍💥 Broken Chain](https://emojipedia.org/broken-chain/?ref=blog.emojipedia.org)

The four new family emojis are:

[🧑‍🧑‍🧒 Family: Adult, Adult, Child](https://emojipedia.org/family-adult-adult-child/?ref=blog.emojipedia.org)
    [🧑‍🧒‍🧒 Family: Adult, Child, Child](https://emojipedia.org/family-adult-child-child/?ref=blog.emojipedia.org)
    [🧑‍🧒 Family: Adult, Child](https://emojipedia.org/family-adult-child/?ref=blog.emojipedia.org)
    [🧑‍🧑‍🧒‍🧒 Family: Adult, Adult, Child, Child](https://emojipedia.org/family-adult-adult-child-child/?ref=blog.emojipedia.org)

The six people emoji characters that now have direction-specifying variations are:

[🚶‍➡️ Person Walking Facing Right](https://emojipedia.org/person_walking_facing_right/?ref=blog.emojipedia.org)
    [🏃‍➡️ Person Running Facing Right](https://emojipedia.org/person_running_facing_right/?ref=blog.emojipedia.org)
    [🧎‍➡️ Person Kneeling Facing Right](https://emojipedia.org/person_kneeling_facing_right/?ref=blog.emojipedia.org)
    [🧑‍🦯‍➡️ Person with White Cane Facing Right](https://emojipedia.org/person_with_white_cane_facing_right/?ref=blog.emojipedia.org)
    [🧑‍🦽‍➡️ Person in Manual Wheelchair Facing Right](https://emojipedia.org/person_in_manual_wheelchair_facing_right/?ref=blog.emojipedia.org)
    [🧑‍🦼‍➡️ Person in Motorized Wheelchair Facing Right](https://emojipedia.org/person_in_motorized_wheelchair_facing_right/?ref=blog.emojipedia.org)

**Comment by b-g** [comment]
Many thanks for the reminder. We are aware of this :)

**Comment by b-g** [comment]
✅ https://github.com/hfg-gmuend/openmoji/commit/13942cdd65134df8899ed5df62ccf47b36d643d7
