### ISSUE TITLE
Improving consistency with other platforms - 12.1

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#72]
## Faces

- [x] Grimacing face isn't consistent - #61 
- [x]     Eyes should be to the right and not centered  [Smirking Face](https://emojipedia.org/smirking-face/) and [Unamused Face](https://emojipedia.org/unamused-face/)  - #74
- [x]   [face screaming in fear](https://emojipedia.org/face-screaming-in-fear/ ) Hands should be clasped around the face not towards the eyes #85 
- [x] [beaming face](https://emojipedia.org/grinning-face-with-smiling-eyes/) doesn't have bottom teeth showing - from issue #82 - #88 
- [x] [frowning face with open mouth](https://emojipedia.org/frowning-face-with-open-mouth/) - shouldn't have eyebrows - #100 
- [x] [tired](https://emojipedia.org/tired-face/) and [weary face](https://emojipedia.org/weary-face/) emoji consistently has a wide, down turned, open mouth — whereas our emojis have a closed mouth. - from #67 - #100 - 6fff9f07
- [x] If we are using big eyes like so [face with rolling eyes](https://emojipedia.org/face-with-rolling-eyes/) we should have similarly big eyes for [flushed face](https://emojipedia.org/flushed-face/) and [face with pleading eyes](https://emojipedia.org/face-with-pleading-eyes/ ) - #100 - f0d9f9f
- [ ]     [Shocked Face with Exploding Head](https://emojipedia.org/shocked-face-with-exploding-head/) looks like some sort of crown but should have a cloud of smoke emanating (we use this emoji as an example of line art on the contributions page)
- [ ] [face with look of triumph](https://emojipedia.org/face-with-look-of-triumph/) - complete redesign - There should be some steam coming out of nose 
- [ ]  [serious face with symbols covering mouth](https://emojipedia.org/serious-face-with-symbols-covering-mouth/) - redesign - There are no symbols covering the mouth and the emoji should potentially be red

### Face emojis with hands 
We have 5 fingers in these emoji [Face With Finger Covering Closed Lips](https://emojipedia.org/face-with-finger-covering-closed-lips/) and [Thinking Face](https://emojipedia.org/thinking-face/) and I think we should have 5 fingers in these emoji too
- [ ]     4 fingers - [smiling face with smiling eyes and hand covering mouth](https://emojipedia.org/smiling-face-with-smiling-eyes-and-hand-covering-mouth/)
- [ ]     4 fingers - [Yawning Face](https://emojipedia.org/yawning-face/)
- [ ]     4 fingers - [Hugging Face]( https://emojipedia.org/hugging-face/) Also hands are too low

## Other

- [x] [melon](https://emojipedia.org/melon/) Should go green, orange, dark orange into the center #79 
- [x] [dumpling](https://emojipedia.org/dumpling/) Should be white - #80 
- [x] [foot](https://emojipedia.org/foot/)  Heel should be fully rounded and there should be a ridge on the top of the foot - #89 
- [x] [Seychelles flag](https://emojipedia.org/flag-for-seychelles/) should meet at a point - #90
- [x] [right anger bubble](https://emojipedia.org/right-anger-bubble/), [thought balloon](https://emojipedia.org/thought-balloon/) and [speech balloon](https://emojipedia.org/speech-balloon/) should all be flipped on the verticle axis - #92 
- [x] [footprints]( https://emojipedia.org/footprints/ ) Too simple, should have some curves - #94 
- [x] [bikini](https://emojipedia.org/bikini/) Pieces should be bigger and closer together - fb866b5
- [x] [banana](https://emojipedia.org/banana/) Too curvy, looks like a crescent moon - 1d94e43
- [ ] [ok hand sign](https://emojipedia.org/ok-hand-sign/) This and Pinching Hand above look like they have webbed fingers. - #86 
- [ ] [pinching fingers](https://emojipedia.org/pinching-hand/)  Pinching fingers should be closer
- [ ] [raccoon](https://emojipedia.org/🦝/) - redesign - should potentially be face on, right now it isn't distinctive enough, looks like a sort of lemur or monkey

Very happy to discuss and back down from any of these suggestions, also will add any issues to this post if they are raised below

**Comment by dnlutz** [comment]
Thank you very much for your list @carlinmack 

The problem is not only consistency with other platforms but also design and quality of our OpenMoji. We are Unicode complete but far away from perfect:
https://twitter.com/honeybeedaehwi/status/1194412693106515969?s=20

We need a strategy to encourage people from outside to contribute and improve the design (and svg/outline) quality. I have some ideas how we could achieve this but I need some time to write it down / develop a concept.

**Comment by carlinmack** [comment]
The feet emoji listed is actually our good feet emoji! 
![image](https://user-images.githubusercontent.com/6676843/69081449-fc2dcf00-0a0b-11ea-801d-5ebdf7d513ba.png)

I have a bunch of design stuff I'm working on right now but a lot of those are very easy fixes (the ones with moving or scaling eyes) so I'm gonna be submitting a bunch of PRs in the coming weeks. 

Have you seen my emails about EmojiNation and such? I would love to talk longer over email with you and @b-g about collaborating with them on new emoji proposals.

**Comment by carlinmack** [comment]
Closing this to replace with issues (#105 #106) for the next iteration
